export const LOAD_DATATYPES_BEGIN = 'LOAD_DATATYPES_BEGIN';
export const LOAD_DATATYPES_SUCCESS = 'LOAD_DATATYPES_SUCCESS';
export const LOAD_DATATYPES_FAILURE = 'LOAD_DATATYPES_FAILURE';

export const LOAD_DATATYPE_BEGIN = 'LOAD_DATATYPE_BEGIN';
export const LOAD_DATATYPE_SUCCESS = 'LOAD_DATATYPE_SUCCESS';
export const LOAD_DATATYPE_FAILURE = 'LOAD_DATATYPE_FAILURE';

export const LOAD_DATAFILES_BEGIN = 'LOAD_DATAFILES_BEGIN';
export const LOAD_DATAFILES_SUCCESS = 'LOAD_DATAFILES_SUCCESS';
export const LOAD_DATAFILES_FAILURE = 'LOAD_DATAFILES_FAILURE';

export const LOAD_DATASUBTYPES_BEGIN = 'LOAD_DATASUBTYPES_BEGIN';
export const LOAD_DATASUBTYPES_SUCCESS = 'LOAD_DATASUBTYPES_SUCCESS';
export const LOAD_DATASUBTYPES_FAILURE = 'LOAD_DATASUBTYPES_FAILURE';

export const LOAD_SCHEMAVERSIONS_BEGIN = 'LOAD_SCHEMAVERSIONS_BEGIN';
export const LOAD_SCHEMAVERSIONS_SUCCESS = 'LOAD_SCHEMAVERSIONS_SUCCESS';
export const LOAD_SCHEMAVERSIONS_FAILURE = 'LOAD_SCHEMAVERSIONS_FAILURE';

export const LOAD_SCHEMAVERSION_BEGIN = 'LOAD_SCHEMAVERSION_BEGIN';
export const LOAD_SCHEMAVERSION_SUCCESS = 'LOAD_SCHEMAVERSION_SUCCESS';
export const LOAD_SCHEMAVERSION_FAILURE = 'LOAD_SCHEMAVERSION_FAILURE';
